export interface PortfolioItem {
  id: string;
  businessName: string;
  industry: string;
  industrySlug: string;
  description: string;
  icon: string;
  color: string;
  bgColor: string;
  tags: string[];
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: "1",
    businessName: "Collins Electrical",
    industry: "Electricians",
    industrySlug: "electricians",
    description: "Local electrician covering Essex. Full services page, certifications, and emergency callout CTA.",
    icon: "⚡",
    color: "#f59e0b",
    bgColor: "#fef3c7",
    tags: ["Contact Form", "Gallery", "SEO"],
  },
  {
    id: "2",
    businessName: "Glow Beauty Studio",
    industry: "Beauty",
    industrySlug: "beauty",
    description: "Luxury beauty salon in Kent. Treatment menu, portfolio gallery, and online booking.",
    icon: "💅",
    color: "#ec4899",
    bgColor: "#fce7f3",
    tags: ["Online Booking", "Gallery", "Pricing"],
  },
  {
    id: "3",
    businessName: "Dragon Spirit Karate",
    industry: "Karate Clubs",
    industrySlug: "karate-clubs",
    description: "Martial arts club in Cardiff. Timetable, instructor profiles, and trial class form.",
    icon: "🥋",
    color: "#ef4444",
    bgColor: "#fee2e2",
    tags: ["Timetable", "Booking", "Gallery"],
  },
  {
    id: "4",
    businessName: "JP Personal Training",
    industry: "Personal Trainers",
    industrySlug: "personal-trainers",
    description: "London-based PT. Transformation gallery, package pricing, and consultation booking.",
    icon: "💪",
    color: "#8b5cf6",
    bgColor: "#ede9fe",
    tags: ["Gallery", "Pricing", "Booking"],
  },
  {
    id: "5",
    businessName: "Okonkwo Plumbing",
    industry: "Plumbers",
    industrySlug: "plumbers",
    description: "Birmingham plumber. Emergency callout banner, Gas Safe badge, and quote form.",
    icon: "🔧",
    color: "#3b82f6",
    bgColor: "#dbeafe",
    tags: ["Emergency CTA", "SEO", "Contact Form"],
  },
  {
    id: "6",
    businessName: "The Copper Kettle",
    industry: "Restaurants",
    industrySlug: "restaurants",
    description: "Manchester restaurant. Full menu, reservation form, and food photography gallery.",
    icon: "🍽️",
    color: "#f97316",
    bgColor: "#ffedd5",
    tags: ["Menu", "Reservations", "Gallery"],
  },
  {
    id: "7",
    businessName: "Peak Performance Gym",
    industry: "Gyms",
    industrySlug: "gyms",
    description: "Independent gym in Leeds. Class timetable, membership pricing, and free trial signup.",
    icon: "🏋️",
    color: "#10b981",
    bgColor: "#d1fae5",
    tags: ["Timetable", "Pricing", "Signup"],
  },
  {
    id: "8",
    businessName: "Clarity Consulting",
    industry: "Consultants",
    industrySlug: "consultants",
    description: "Business consultant in London. Case studies, blog, and discovery call booking.",
    icon: "📊",
    color: "#0ea5e9",
    bgColor: "#e0f2fe",
    tags: ["Blog", "Case Studies", "Booking"],
  },
  {
    id: "9",
    businessName: "ProBuild Contractors",
    industry: "Builders",
    industrySlug: "builders",
    description: "Surrey building contractor. Project gallery, testimonials, and quote request form.",
    icon: "🏗️",
    color: "#78716c",
    bgColor: "#f5f5f4",
    tags: ["Gallery", "Testimonials", "Quote Form"],
  },
  {
    id: "10",
    businessName: "Zenith Life Coaching",
    industry: "Coaches",
    industrySlug: "coaches",
    description: "Life and business coach. Programme details, client results, and free call booking.",
    icon: "🎯",
    color: "#6366f1",
    bgColor: "#eef2ff",
    tags: ["Programmes", "Booking", "Testimonials"],
  },
  {
    id: "11",
    businessName: "Sharp Eye Photography",
    industry: "Photographers",
    industrySlug: "photographers",
    description: "Commercial photographer. Portfolio, package pricing, and enquiry form.",
    icon: "📸",
    color: "#374151",
    bgColor: "#f3f4f6",
    tags: ["Portfolio", "Pricing", "Contact"],
  },
  {
    id: "12",
    businessName: "Meridian Accountants",
    industry: "Accountants",
    industrySlug: "accountants",
    description: "Accountancy practice in Bristol. Services, pricing, and new client enquiry form.",
    icon: "📑",
    color: "#0284c7",
    bgColor: "#e0f2fe",
    tags: ["Services", "Pricing", "Contact Form"],
  },
  {
    id: "13",
    businessName: "Forza Karate Club",
    industry: "Karate Clubs",
    industrySlug: "karate-clubs",
    description: "Professional martial arts club site with belt progression, instructor profiles, competition results, members area, and trial class booking.",
    icon: "🥋",
    color: "#dc2626",
    bgColor: "#fee2e2",
    tags: ["Members Area", "Gallery", "Gradings"],
  },
  {
    id: "14",
    businessName: "JHKA",
    industry: "Karate Clubs",
    industrySlug: "karate-clubs",
    description: "Wado Ryu karate association site with 21-grade progression system, class timetable, safeguarding pages, and a protected members area.",
    icon: "🥋",
    color: "#2563eb",
    bgColor: "#dbeafe",
    tags: ["Timetable", "Gradings", "Members Area"],
  },
  {
    id: "15",
    businessName: "JGFA",
    industry: "Football Clubs",
    industrySlug: "football-clubs",
    description: "Local football club site with squad info, fixtures & results, membership signup, and a contact form for new players.",
    icon: "⚽",
    color: "#16a34a",
    bgColor: "#dcfce7",
    tags: ["Fixtures", "Squad", "Membership"],
  },
  {
    id: "16",
    businessName: "Scott Nicholls",
    industry: "Hobby Pages",
    industrySlug: "hobby-pages",
    description: "Personal hobby page showcasing interests, projects, and a blog — a clean space to share what you love with the world.",
    icon: "🌟",
    color: "#7c3aed",
    bgColor: "#ede9fe",
    tags: ["About", "Blog", "Gallery"],
  },
];

export const industryFilters = [
  "All",
  "Electricians",
  "Plumbers",
  "Karate Clubs",
  "Football Clubs",
  "Personal Trainers",
  "Restaurants",
  "Beauty",
  "Gyms",
  "Consultants",
  "Builders",
  "Coaches",
  "Hobby Pages",
];
